<a href="https://colab.research.google.com/github/tomasm0703/ANN-MNIST-dataset/blob/main/ANN_MNIST_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
train_data = pd.read_csv("https://drive.google.com/file/d/1WZyz2OEqlhCvPom7W6tiQMBDc6i7dcJk/view?usp=sharing")

In [5]:
train_data.describe()

,utm_source,utm_medium,utm_term,utm_content,sle],"docs-doddn:""""",0.1,0.2,docs-eccfs:false,docs-eefufd:false,...,0.86,0.87,0.88,0.89,1].11,[[null.2,null.204,null.205,"https://www.gstatic.com/og/_/js/k=og.qtm.en_US.K5UqK6Zqv4E.es5.O/rt=j/m=qabr,q_dnp,qapid/exm=qaaw,qadd,qaid,qein,qhaw,qhba,qhbr,qhch,qhga,qhid,qhin/d=1/ed=1/rs=AA2YrTtsJO8LSHiXTXntakQJaGv_V483sA]]]]",};this.gbar_=this.gbar_||{};(function(_){var window=this;
count,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64.0,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN